/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#0f426f',
        'primary-container':          '#2e5a88',
        'primary-fixed':              '#d2e4ff',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#aed1ff',
        'secondary':                  '#456648',
        'secondary-container':        '#c3e9c3',
        'secondary-fixed':            '#c6ecc6',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#496a4c',
        'tertiary':                   '#5f360b',
        'tertiary-container':         '#7b4d20',
        'tertiary-fixed':             '#ffdcc1',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#ffc28d',
        'surface':                    '#fdf9f1',
        'surface-variant':            '#e6e2db',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f7f3ec',
        'surface-container':          '#f1ede6',
        'surface-container-high':     '#ece8e0',
        'surface-container-highest':  '#e6e2db',
        'on-surface':                 '#1c1c17',
        'on-surface-variant':         '#42474f',
        'outline':                    '#737780',
        'outline-variant':            '#c2c7d0',
        'primary-fixed-dim':          '#a0cafe',
        'tertiary-fixed-dim':         '#f8ba83',
        'secondary-fixed-dim':        '#abd0ab',
        'inverse-surface':            '#31302c',
        'inverse-on-surface':         '#f4f0e9',
        'inverse-primary':            '#a0cafe',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
        'background':                 '#fdf9f1',
        'on-background':              '#1c1c17',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Public Sans', 'sans-serif'],
        label:    ['Public Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
